labelPRBasedOnFilePath:
  need review:
    - "config/**"
    - "script/**"
    - "resourcepacks/**"
    - "resources/**"
    - "kubejs/assets/**"
    
  1.54:
    - "config/**"
    - "script/**"
    - "resourcepacks/**"
    - "resources/**"
    - "kubejs/assets/**"

  .github:
    - ".github/**"

  resource:
    - "resourcepacks/**"
    - "resources/**"
    - "kubejs/assets/**"

  ftbquest:
    - "config/ftbquests/**"

labelerFlags:
    labelOnPRUpdates: true  
