labelPRBasedOnFilePath:
  need review:
    - "config/**"
    - "script/**"
    - "resourcepacks/**"
    - "resources/**"
    
  1.56:
    - "config/**"
    - "script/**"
    - "resourcepacks/**"
    - "resources/**"

  .github:
    - ".github/**"

  resource:
    - "resourcepacks/**"
    - "resources/**"

  ftbquest:
    - "config/ftbquests/**"

labelerFlags:
    labelOnPRUpdates: true  
